export const APPEND_TRANSACTION_PIN_DATA= "APPEND_TRANSACTION_PIN_DATA";
export const TNX_PIN_MODAL_STATE= "TNX_PIN_MODAL_STATE";
export const IS_TNX_PIN_PROVIDED= "IS_TNX_PIN_PROVIDED";
export const DELETE_TRANSACTION_PIN_DATA= "DELETE_TRANSACTION_PIN_DATA";
export const CLEAR_TRANSACTION_PIN_DATA= "CLEAR_TRANSACTION_PIN_DATA";
export const NEXT_METHOD_AFTER_TNX_PIN= "NEXT_METHOD_AFTER_TNX_PIN";